const ROUTES = {
  ONBOARDING_INTRO: 'ONBOARDING_INTRO',
  MAIN_SCENE: 'MAIN_SCENE',
};

const VALUES = {
  QUESTION_MULTIPLE_CHOICE: 'multiple',
  DEFAULT_TYPE_QUESTIONS: 'boolean',
  DEFAULT_AMOUNT_QUESTIONS: 10,
  BOOLEAN_FALSE_VALUE: 'False',
  QUESTION_BOOLEAN: 'boolean',
  BOOLEAN_TRUE_VALUE: 'True',
  ANY_PARAM: '@ANY_PARAM',
  DIFFICULTY_PARAM_FIELD: 'difficulty',
  CATEGORY_PARAM_FIELD: 'category',
  AMOUNT_PARAM_FIELD: 'amount',
  TYPE_PARAM_FIELD: 'type',
  API_NO_RESULT: 1,
};

const PARAMS = {
  SHOULD_SHOW_QUESTIONS_RESTART_BUTTON: 'SHOULD_SHOW_QUESTIONS_RESTART_BUTTON',
  RESTART_QUESTIONS: 'RESTART_QUESTIONS',
  QUESTIONS_PARAMS: 'QUESTIONS_PARAMS',
  USER_ANSWERS: 'USER_ANSWERS',
};

export default {
  PARAMS,
  ROUTES,
  VALUES,
};
